#!/usr/bin/env bash

ALL_ARGS=$@

BUILD=no
for i in "$@":
do
  case $i in
    --build)
    BUILD=yes
    ;;
    *)
    ;;
  esac
done

if [ $BUILD == "yes" ]; then
  cmake "$@"
else
  cmake \
      -DANDROID_ABI=$ANDROID_ABI \
      -DANDROID_PLATFORM=$ANDROID_PLATFORM \
      "$@"
fi
