image: registry.gitlab.com/studyintonation/repositories/docker/conan-android:latest

variables:
  CONAN_LOGIN_USERNAME_GITLAB: ci_user
  CONAN_PASSWORD_GITLAB: ${CI_JOB_TOKEN}


# Packages installation before running script
before_script:
  # Check the sdkmanager
  - sdkmanager --version

  # Not necessary, but just for surity
  - chmod +x ./gradlew

  # Fetch the Oboe submodule
  - git submodule update --init --recursive

  # Add Cmake to the path
  - export PATH=$PATH:${ANDROID_HOME}/cmake/3.18.1/bin

# Assemble and publish to Gitlab Artifacts
#assemble:
#  interruptible: true
#  stage: build
#  script:
#    - ./gradlew android:assemble
#  artifacts:
#    paths:
#      - android/build/outputs/aar

# Assemble and publish to internal Maven repository
assemble:
  stage: build
  script:
    - ./gradlew publish

# Run all tests, if any fails, interrupt the pipeline(fail it)
# debugTests:
#   interruptible: true
#   stage: test
#   script:
#     - ./gradlew -Pci --console=plain :app:testDebug
